apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-dashboard
spec:
  template:
    spec:
      containers:
        - name: devops-dashboard
          image: 123456789012.dkr.ecr.ap-northeast-2.amazonaws.com/devops-dashboard:latest

