replicaCount: 1

image:
  repository: your-ecr-repo
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: LoadBalancer
  port: 8501

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 250m
    memory: 256Mi
